version: '3'

services:
    service:
        image: ${RELEASE_IMAGE_TAG}
        ports:
            - "80:80"
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 5s
