version: '3'

services:
    service:
        image: ${TEST_IMAGE_TAG}

    service_tests:
        image: $DOCKER_HUB_USERNAME/service_tests
        build: docker/service_tests/
        depends_on:
            - service

    # optionally, add other services that are needed to
    # run the service tests
